Repository benavlabs/fastcrud, pull requests merged in 2024-06, with the labels that each got.

#85 Missing sqlalchemy operators
  docs/advanced/crud.md
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/core/test_parse_filters.py
  tests/sqlmodel/core/test_parse_filters.py
Labels: enhancement, FastCRUD Methods

#107 null primary key bug fixed
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/core/test_parse_filters.py
  tests/sqlalchemy/crud/test_get_joined.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/core/test_parse_filters.py
  tests/sqlmodel/crud/test_get_joined.py
  tests/sqlmodel/crud/test_get_multi_joined.py
Labels: bug

#108 changelog and pyproject
  docs/changelog.md
  pyproject.toml
Labels: documentation

#114 new tests for get_items paginated, coverage at 100%
  fastcrud/endpoint/endpoint_creator.py
  tests/sqlalchemy/endpoint/test_get_paginated.py
  tests/sqlmodel/endpoint/test_get_paginated.py
Labels: enhancement
