Repository benavlabs/fastcrud, pull requests merged in 2024-05, with the labels that each got.

#69 Join fixes
  docs/advanced/joins.md
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  fastcrud/endpoint/helper.py
  mypy.ini
  tests/sqlalchemy/crud/test_get_joined.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlmodel/crud/test_get_joined.py
  tests/sqlmodel/crud/test_get_multi_joined.py
Labels: bug, documentation, FastCRUD Methods

#70 Dependencies
  fastcrud/endpoint/crud_router.py
  fastcrud/endpoint/endpoint_creator.py
  fastcrud/endpoint/helper.py
  tests/sqlalchemy/conftest.py
Labels: bug

#71 Skip commit
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/conftest.py
  tests/sqlmodel/conftest.py
Labels: enhancement

#73 Docstring fix
  docs/advanced/crud.md
  fastcrud/crud/fast_crud.py
Labels: documentation

#57 feat: filter __in
  docs/advanced/crud.md
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/core/test_parse_filters.py
  tests/sqlmodel/core/test_parse_filters.py
Labels: enhancement, FastCRUD Methods

#76 python support for 0.111.0 added
  pyproject.toml
Labels: enhancement

#78 Updated docs
  docs/advanced/crud.md
  docs/changelog.md
  docs/usage/crud.md
Labels: documentation

#82 deprecation warning added to depends
  docs/changelog.md
  fastcrud/crud/fast_crud.py
  fastcrud/endpoint/helper.py
  pyproject.toml
  tests/sqlalchemy/core/test_parse_filters.py
  tests/sqlmodel/core/test_parse_filters.py
Labels: enhancement, Automatic Endpoint

#49 feat: ✨ add upsert method in FastCRUD class
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/crud/test_upsert.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/crud/test_upsert.py
Labels: enhancement, FastCRUD Methods

#87 [WIP] Filters in Automatic Endpoints
  docs/advanced/endpoint.md
  docs/advanced/overview.md
  fastcrud/__init__.py
  fastcrud/crud/fast_crud.py
  fastcrud/endpoint/crud_router.py
  fastcrud/endpoint/endpoint_creator.py
  fastcrud/endpoint/helper.py
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/core/test_filter_config.py
  tests/sqlalchemy/endpoint/test_get_items.py
  tests/sqlalchemy/endpoint/test_get_paginated.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/core/test_filter_config.py
  tests/sqlmodel/endpoint/test_get_items.py
  tests/sqlmodel/endpoint/test_get_paginated.py
Labels: enhancement, Automatic Endpoint

#93 One-to-many support in joins
  docs/advanced/crud.md
  docs/advanced/joins.md
  docs/usage/crud.md
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/core/test_nest_multi_join_data.py
  tests/sqlalchemy/crud/test_get_joined.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/core/test_nest_multi_join_data.py
  tests/sqlmodel/crud/test_get_joined.py
  tests/sqlmodel/crud/test_get_multi_joined.py
Labels: bug, enhancement, FastCRUD Methods

#96 Using the same session for all tests
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/endpoint/test_custom_endpoint_creator.py
  tests/sqlalchemy/endpoint/test_deleted_methods.py
  tests/sqlalchemy/endpoint/test_endpoint_custom_names.py
  tests/sqlalchemy/endpoint/test_included_methods.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/endpoint/test_custom_endpoint_creator.py
  tests/sqlmodel/endpoint/test_deleted_methods.py
  tests/sqlmodel/endpoint/test_endpoint_custom_names.py
  tests/sqlmodel/endpoint/test_included_methods.py
Labels: bug

#97 warning added to docs
  docs/advanced/crud.md
  docs/usage/crud.md
Labels: documentation
