Repository benavlabs/fastcrud, pull requests merged in 2024-04, with the labels that each got.

#31 feat: ✨ add multiple primary keys support
  fastcrud/crud/fast_crud.py
  fastcrud/endpoint/endpoint_creator.py
  fastcrud/endpoint/helper.py
  pyproject.toml
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/crud/test_create.py
  tests/sqlalchemy/endpoint/test_create_item.py
  tests/sqlalchemy/endpoint/test_get_item.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/crud/test_create.py
  tests/sqlmodel/endpoint/test_create_item.py
  tests/sqlmodel/endpoint/test_get_item.py
Labels: enhancement

#42 Test Coverage at 100%
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  fastcrud/endpoint/endpoint_creator.py
  fastcrud/endpoint/helper.py
  fastcrud/exceptions/http_exceptions.py
  pyproject.toml
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/core/__init__.py
  tests/sqlalchemy/core/test_parse_filters.py
  tests/sqlalchemy/core/test_valid_methods.py
  tests/sqlalchemy/crud/test_apply_sorting.py
  tests/sqlalchemy/crud/test_count.py
  tests/sqlalchemy/crud/test_delete.py
  tests/sqlalchemy/crud/test_get.py
  tests/sqlalchemy/crud/test_get_joined.py
  tests/sqlalchemy/crud/test_get_multi.py
  tests/sqlalchemy/crud/test_get_multi_by_cursor.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlalchemy/crud/test_update.py
  tests/sqlalchemy/endpoint/test_custom_route.py
  tests/sqlalchemy/endpoint/test_deleted_methods.py
  tests/sqlalchemy/endpoint/test_included_methods.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/core/__init__.py
  tests/sqlmodel/core/test_parse_filters.py
  tests/sqlmodel/core/test_valid_methods.py
  tests/sqlmodel/crud/test_apply_sorting.py
  tests/sqlmodel/crud/test_count.py
  tests/sqlmodel/crud/test_delete.py
  tests/sqlmodel/crud/test_get.py
  tests/sqlmodel/crud/test_get_joined.py
  tests/sqlmodel/crud/test_get_multi.py
  tests/sqlmodel/crud/test_get_multi_by_cursor.py
  tests/sqlmodel/crud/test_get_multi_joined.py
  tests/sqlmodel/crud/test_update.py
  tests/sqlmodel/endpoint/test_custom_route.py
  tests/sqlmodel/endpoint/test_deleted_methods.py
  tests/sqlmodel/endpoint/test_included_methods.py
Labels: bug, enhancement

#44 Update README.md code coverage badge
  README.md
Labels: documentation

#45 Optional count
  docs/usage/crud.md
  fastcrud/crud/fast_crud.py
  fastcrud/endpoint/helper.py
  tests/sqlalchemy/crud/test_update.py
  tests/sqlalchemy/endpoint/test_custom_route.py
  tests/sqlmodel/crud/test_update.py
  tests/sqlmodel/endpoint/test_custom_route.py
Labels: enhancement

#46 Docs update for 0.11.0
  README.md
  docs/index.md
  pyproject.toml
Labels: enhancement

#47 0.11.0 added to changelog
  docs/changelog.md
Labels: documentation

#48 coverage badge in docs
  docs/index.md
Labels: documentation

#51 Skip count call when possible
  fastcrud/crud/fast_crud.py
Labels: enhancement, FastCRUD Methods

#55 refactor: :recycle: reuse of select method in FastCRUD
  fastcrud/crud/fast_crud.py
Labels: enhancement, FastCRUD Methods

#54 feat: :sparkles: add strict parameter to FastCRUD `get` method
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/crud/test_get.py
  tests/sqlmodel/crud/test_get.py
Labels: enhancement, FastCRUD Methods

#56 Nested responses
  docs/advanced/joins.md
  docs/changelog.md
  docs/usage/crud.md
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  pyproject.toml
  tests/sqlalchemy/crud/test_get_joined.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlmodel/crud/test_get_joined.py
  tests/sqlmodel/crud/test_get_multi_joined.py
Labels: enhancement, FastCRUD Methods

#62 Add unpaginated versions of multi-row get methods (w/tests)
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/crud/test_get_multi.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlmodel/crud/test_get_multi.py
  tests/sqlmodel/crud/test_get_multi_joined.py
Labels: enhancement, FastCRUD Methods
