Repository benavlabs/fastcrud, pull requests merged in 2024-03, with the labels that each got.

#21 16 is there a way to customize the path suffix added by crud router
  docs/advanced/endpoint.md
  fastcrud/endpoint/crud_router.py
  fastcrud/endpoint/endpoint_creator.py
  tests/sqlalchemy/endpoint/test_endpoint_custom_names.py
  tests/sqlmodel/endpoint/test_endpoint_custom_names.py
Labels: enhancement

#23 fix: add necessary package import
  docs/index.md
Labels: documentation

#26 Using `get_joined` and `get_multi_joined` for multiple models
  README.md
  docs/advanced/crud.md
  docs/usage/crud.md
  fastcrud/__init__.py
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  pyproject.toml
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/crud/test_get_joined.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/crud/test_get_joined.py
  tests/sqlmodel/crud/test_get_multi_joined.py
Labels: enhancement

#29 Using Aliases
  docs/advanced/crud.md
  docs/advanced/overview.md
  fastcrud/__init__.py
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/crud/test_get_joined.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/crud/test_get.py
  tests/sqlmodel/crud/test_get_joined.py
  tests/sqlmodel/crud/test_get_multi_by_cursor.py
  tests/sqlmodel/crud/test_get_multi_joined.py
  tests/sqlmodel/crud/test_update.py
Labels: enhancement

#28 feat: :sparkles: add select statement in FastCRUD
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/crud/test_select.py
  tests/sqlmodel/crud/test_select.py
Labels: enhancement

#32 Select method changes and docs
  docs/advanced/crud.md
  docs/advanced/overview.md
  docs/usage/crud.md
  fastcrud/crud/fast_crud.py
  tests/sqlalchemy/crud/test_select.py
  tests/sqlmodel/crud/test_select.py
Labels: bug, documentation

#35 Improved Joins
  docs/advanced/crud.md
  docs/advanced/joins.md
  docs/advanced/overview.md
  docs/usage/crud.md
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  mkdocs.yml
  pyproject.toml
  tests/sqlalchemy/conftest.py
  tests/sqlalchemy/crud/test_count.py
  tests/sqlalchemy/crud/test_get_multi_by_cursor.py
  tests/sqlalchemy/crud/test_get_multi_joined.py
  tests/sqlalchemy/crud/test_select.py
  tests/sqlalchemy/endpoint/test_get_items.py
  tests/sqlalchemy/endpoint/test_update_item.py
  tests/sqlmodel/conftest.py
  tests/sqlmodel/crud/test_count.py
  tests/sqlmodel/crud/test_get_multi_by_cursor.py
  tests/sqlmodel/crud/test_get_multi_joined.py
  tests/sqlmodel/crud/test_select.py
  tests/sqlmodel/endpoint/test_get_items.py
  tests/sqlmodel/endpoint/test_update_item.py
Labels: bug, documentation, enhancement

#36 Type checking
  .github/workflows/type-check.yml
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  fastcrud/endpoint/crud_router.py
  fastcrud/endpoint/endpoint_creator.py
  fastcrud/endpoint/helper.py
  pyproject.toml
Labels: bug, enhancement

#37 Linting
  .github/workflows/linting.yml
  pyproject.toml
Labels: enhancement

#38 version in pyproject bumped
  pyproject.toml
Labels: documentation

#40 changelog docs
  docs/advanced/joins.md
  docs/changelog.md
  mkdocs.yml
Labels: documentation
