Repository benavlabs/fastcrud, pull requests merged in 2024-07, with the labels that each got.

#129 vulnerability fixed with outdated cryptography package
  pyproject.toml
Labels: bug

#127 Models and Schemas, Batch 1: Simple/One-Off Models
  docs/advanced/crud.md
  docs/advanced/endpoint.md
  docs/index.md
  docs/quick-start.md
  docs/sqlmodel.md
  docs/usage/crud.md
  docs/usage/endpoint.md
  fastcrud/crud/fast_crud.py
  fastcrud/endpoint/crud_router.py
  fastcrud/endpoint/endpoint_creator.py
  fastcrud/examples/item/model.py
  fastcrud/examples/item/schemas.py
  fastcrud/examples/item/sqlmodel.py
  fastcrud/examples/mymodel/model.py
  fastcrud/examples/mymodel/schemas.py
  mkdocs.yml
Labels: documentation

#139 Preparations for 0.14.0
  docs/changelog.md
  docs/usage/endpoint.md
  fastcrud/crud/fast_crud.py
  fastcrud/crud/helper.py
  fastcrud/endpoint/helper.py
  pyproject.toml
  tests/sqlalchemy/conftest.py
  tests/sqlmodel/conftest.py
Labels: enhancement
